### ISSUE TITLE
Bug Report: VR user kicked from world (without disconnecting)

### ISSUE THREAD

**Issue by peregrinefu** [PlumCantaloupe/circlesxr#198]
Setup:
- User attempted to switch to hub (campfire world) while "holding" a parent-constraint object (e.g. "lunch" in "on the job").
- Instead of returning to hub, Oculus browser stopped running on user's HMD.
- Socket.io did not list the user as disconnected.

Notes:
- Seemingly replicable on any world with parent-constraint objects.
- Issue does not arise on desktop use. Seemingly an "immersive experience" issue.

Possible fixes:
- Automatically "put back" any parent-constrained object when switching between worlds?

**Comment by PlumCantaloupe** [comment]
Thanks. I will take a look at this. Your workaround sounds reasonable.

**Comment by PlumCantaloupe** [comment]
Working on a big PR that should be in soon that rewrites how pickup/release is done. Hopefully this will help.

**Comment by PlumCantaloupe** [comment]
I have tested on a Quest1 and Quest2 and this issue appears to have been resolved with the new interaction system, now in the main branch.
