### ISSUE TITLE
Bug report: circles-artefact.js contains an unused variable reference that is set by a non-existent function

### ISSUE THREAD

**Issue by colinarelliott** [PlumCantaloupe/circlesxr#205]
Line 29 in *circles-artefact.js*

```js
const world  = document.querySelector('[circles-manager]').components['circles-manager'].getWorld();
```

`getWorld()` is not a function in this scope and `world` is an unused variable, this can be fixed by just deleting the line (as I have hacked in on my branch)

**Comment by PlumCantaloupe** [comment]
Ah, thank you. I have removed the line. See here: 4081d5ad2269101fc42d6f26e117aac3b5412996
