### ISSUE TITLE
Dropping Artefact inconsistencies

### ISSUE THREAD

**Issue by ElisVoid333** [PlumCantaloupe/circlesxr#227]
https://github.com/user-attachments/assets/997f1f50-d45f-49ec-aacb-40936bfb3af8

https://github.com/user-attachments/assets/b20a6db2-4ee8-4dff-b95c-2d2450ab9e39

Specifically differences between this version(second vid) and the version running on circlesxr.com(first vid, online version).

The online version has the issue of labels not properly resizing after deselect fixed and this version does not. I am wondering if this is a local issue or something else.

**Comment by PlumCantaloupe** [comment]
Hello! Can try the dev branch and see if this fixes the issue for you? (don't forget to npm install again as packages and aframe have also been updated).

You see more at this PR: #228
